# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-TT2Site
version:      0.95
version_from: 
installdirs:  site
requires:
    AppConfig:                     1.56
    Getopt::Long:                  2.1
    Template:                      2.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
