#!/usr/bin/perl -w
my $RCS_Id = '$Id: tt2site,v 1.3 2004/12/29 16:08:19 jv Exp $ ';

# Author          : Johan Vromans
# Created On      : Mon Dec  6 21:48:07 2004
# Last Modified By: Johan Vromans
# Last Modified On: Wed Dec 29 15:17:53 2004
# Update Count    : 122
# Status          : Unknown, Use with caution!

################ Common stuff ################

use strict;

# Package name.
my $my_package = 'TT2Site';
# Program name and version.
my ($my_name, $my_version) = $RCS_Id =~ /: (.+),v ([\d.]+)/;
# Tack '*' if it is not checked in into RCS.
$my_version .= '*' if length('$Locker:  $ ') > 12;

################ The Process ################

BEGIN {
    if ( $ENV{TT2SITE_LIB} ) {
	unshift(@INC, $ENV{TT2SITE_LIB});
    }
}

use Template::TT2Site;

@ARGV = qw(build) unless @ARGV;

if ( $ARGV[0] =~ /^-+(i(dent)?|V(ersion)?)$/i ) {
    shift(@ARGV);
    print("This is $my_package [$my_name $my_version] ",
	  "using Template::TT2Site version ",
	  $Template::TT2Site::VERSION, "\n");
    exit(0);
}

Template::TT2Site->execute(@ARGV);

__END__

=head1 NAME

tt2site - Template Toolkit site builder

=head1 SYNOPSIS

tt2site [options] [setup|build|rebuild|clean|realclean]

Options:

   --ident		show identification

=head1 COMMANDS

=over 8

=item B<setup>

Initialises a new site directory. This command must be run once before
you can do anything else.

=item B<build>

Run the C<ttree> application to update the site files.

=item B<rebuild>

Run the C<ttree> application to completely rebuild all site files.

=item B<clean>

Cleans the generated HTML files, and editor backup files.

=item B<realclean>

Cleans the generated HTML files, editor backup files, and all files
originally installed using the B<setup> command.

You'll be asked for confirmation before your files are removed.

=back

=head1 OPTIONS

=over 8

=item B<--verbose>

More verbose information.

=item B<--version>

Print a version identification to standard output and exits.

=item B<--help>

Print a brief help message to standard output and exits.

=item B<--ident>

Prints a program identification.

=back

=head1 DESCRIPTION

B<tt2site> is the main tool to use the C<Template::TT2Site> program.

=head1 AUTHOR

Johan Vromans <jvromans@squirrel.nl>

=head1 COPYRIGHT

This programs is Copyright 2004-2005, Squirrel Consultancy.

This program is free software; you can redistribute it and/or modify
it under the terms of the Perl Artistic License or the GNU General
Public License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

=cut
